name: MakeEmSpawn
main: com.hybris.bukkit.makeemspawn.MakeEmSpawn
version: 1.1
website: 
author: Hybris95
description: 
             MakeEmSpawn allows (ops/permissionned) players to (de)spawn monsters
commands:
    makeemspawn:
        aliases:
            mes